language: node_js
node_js:
  - "7"
env:
  CODECLIMATE_REPO_TOKEN: 9de0431ee41158f3a57ecffd9f38de7d6e7482e590b08fa2acdb2cd0923f419d
cache:
  directories:
    - "node_modules"
sudo: false
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE weconnect-test;' -U postgres
  - npm run test-migrate
after_success: 
  - npm run coverage
  - npm run codeclimate-report
  - npm run check-coverage