export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const UPDATE_USER = 'UPDATE_USER';
export const POST_REVIEW = 'POST_REVIEW';
export const POST_REVIEW_RESPONSE = 'POST_REVIEW_RESPONSE';
export const FETCH_BUSINESS_REVIEWS = 'FETCH_BUSINESS_REVIEWS';
export const FETCH_BUSINESS_REVIEWS_FAILED = 'FETCH_BUSINESS_REVIEWS_FAILED';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const SET_BUSINESS_PROFILE = 'SET_BUSINESS_PROFILE';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const FETCH_BUSINESS = 'FETCH_BUSINESS';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const FETCH_USER_BUSINESSES = 'FETCH_USER_BUSINESSES';
export const FETCH_USER_BUSINESSES_FAILED = 'FETCH_USER_BUSINESSES_FAILED';

